theme: jekyll-theme-minimal
show_downloads: "true"
logo: /misc/logo.png
github:
  tar_url: https://github.com/goirijo/multishifter/releases/download/v1.0.0/multishifter-1.0.0.tar.gz
  zip_url: https://github.com/goirijo/multishifter/releases/download/v1.0.0/multishifter-1.0.0.zip
github_username: goirijo
markdown: kramdown
